// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1WJiKWs6SVTGFzP0fXmdS6duRN2T2Kmw',
    appId: '1:470527456424:web:c79d5330aedcbeafa77e9d',
    messagingSenderId: '470527456424',
    projectId: 'xrg-mini-proj',
    authDomain: 'xrg-mini-proj.firebaseapp.com',
    storageBucket: 'xrg-mini-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCac8qptuCznJJ1gJafBBJPq_ANqUC-xnQ',
    appId: '1:470527456424:android:15de861c711f8421a77e9d',
    messagingSenderId: '470527456424',
    projectId: 'xrg-mini-proj',
    storageBucket: 'xrg-mini-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7xhLPdAfsmpnR1s37O7nlRDSbZSJdmE',
    appId: '1:470527456424:ios:ef272820e9777f69a77e9d',
    messagingSenderId: '470527456424',
    projectId: 'xrg-mini-proj',
    storageBucket: 'xrg-mini-proj.appspot.com',
    iosBundleId: 'com.example.miniproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7xhLPdAfsmpnR1s37O7nlRDSbZSJdmE',
    appId: '1:470527456424:ios:5e1d368108098333a77e9d',
    messagingSenderId: '470527456424',
    projectId: 'xrg-mini-proj',
    storageBucket: 'xrg-mini-proj.appspot.com',
    iosBundleId: 'com.example.miniproj.RunnerTests',
  );
}
